name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@main
        with:
          USERNAME: bhavy1204
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Generated 3D contribution graph'
